enum Priority {
  LOW
  MEDIUM
  HIGH
}

type Product @collection(name: "products") {
  name: String!
  priority: Priority!
  purchased: Boolean!
  list: List
}

type List @collection(name: "lists") {
  id: String!
  name: String!
  products: [Product!] @relation
}

type Query {
  listById(id: String!): List!
  productsByList(lsit_id: String!): [Product!] @resolver(name: "list_by_id", paginated: true)
}

# list_by_id UDF
# Query(
#   Lambda(
#     ["id", "X", "Y", "ref"],
#     Reverse(
#       Map(
#         Paginate(
#           Match(
#             Index("list_products_by_list"),
#             Select("ref", Get(Match(Index("list_by_id"), Var("id"))))
#           )
#         ),
#         Lambda("ref", Get(Var("ref")))
#       )
#     )
#   )
# )
